import { access, readFile, readdir } from 'node:fs/promises';
import { constants } from 'node:fs';
import { execFileSync } from 'node:child_process';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const root=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'..');
const jsDir=path.join(root,'assets','js');
const failures=[];
const required=[
  'index.html','register.html','login.html','forgot-password.html','reset-password.html','admin-dashboard.html','listings.html','listing.html','business.html','trip-results.html','traveler-register.html','traveler-dashboard.html',
  'operator-overview.html','operator-dashboard.html','operator-calendar.html','operator-reservations.html','operator-content.html','operator-rates.html','operator-reviews.html','operator-analytics.html','operator-settings.html','operator-inbox.html','operator-availability.html','operator-payments.html','operator-more.html',
  '.env.example','config.example.js','config.js','serve.json','assets/css/operator-v2.css','assets/css/operator-partner-extranet.css','assets/css/operator-audit-fixes-v2.css',
  'assets/js/auth.js','assets/js/operator-shell.js','assets/js/operator-header-layout-v2.js','assets/js/operator-property-v2.js','assets/js/operator-overview-page-v2.js','assets/js/operator-calendar-v2.js','assets/js/operator-calendar-hardening-v2.js','assets/js/operator-reservations-v2.js','assets/js/operator-content-v2.js','assets/js/operator-listing-advanced-v2.js','assets/js/operator-room-media-v2.js','assets/js/operator-content-enhancements.js','assets/js/operator-rates-v2.js','assets/js/operator-reviews-v2.js','assets/js/operator-analytics-v2.js','assets/js/operator-settings-v2.js','assets/js/operator-inbox-v2.js','assets/js/operator-availability.js','assets/js/operator-external-booking-edit-v2.js','assets/js/operator-payments-v2.js','assets/js/operator-more-v2.js','assets/js/operator-action-locks-v2.js','assets/js/operator-notifications.js',
  'assets/js/manta-planner.js','assets/js/trip-planner-service.js','assets/js/trip-results.js','assets/js/pricing.js','assets/js/storage.js','assets/js/supabase-client.js','assets/css/manta-planner.css','assets/css/trip-results.css','assets/images/manta-planner.png',
  'supabase/migrations/20260825074051_retire_operator_v1_duplicate_rpcs.sql','supabase/migrations/20260825104633_operator_v2_audit_hardening.sql','supabase/migrations/20260825105332_operator_finance_queue_complete.sql','supabase/migrations/20260825114106_operator_v2_audit_finalization.sql','supabase/migrations/20260825114822_operator_calendar_staff_visibility.sql'
];
for(const file of required){try{await access(path.join(root,file),constants.R_OK);}catch{failures.push(`Missing required file: ${file}`);}}

const retiredModules=['operator-dashboard.js','operator-dashboard-retire-legacy-v2.js','operator-onboarding-simple.js','operator-overview-v2.js','operator-external-bookings-compat-v2.js','operator-category-unlock-v2.js','operator-listing-enhancements-v2.js','operator-home-partner-v3.js','operator-calendar-submit-guard-v2.js','operator-content-compat-v2.js'];
for(const file of retiredModules){try{await access(path.join(jsDir,file),constants.R_OK);failures.push(`${file}: retired duplicate module still exists`);}catch{}}

const htmlFiles=(await readdir(root)).filter((name)=>name.endsWith('.html'));
for(const file of htmlFiles){const source=await readFile(path.join(root,file),'utf8');const open=(source.match(/<button(?:\s|>)/g)||[]).length,close=(source.match(/<\/button>/g)||[]).length;if(open!==close)failures.push(`${file}: unbalanced button tags (${open}/${close})`);for(const match of source.matchAll(/(?:href|src)="([^"]+)"/g)){const ref=match[1];if(/^(?:https?:|mailto:|tel:|data:|#|javascript:)/i.test(ref))continue;const clean=decodeURIComponent(ref.split(/[?#]/)[0]);if(!clean)continue;try{await access(path.resolve(root,path.dirname(file),clean),constants.R_OK);}catch{failures.push(`${file}: missing local reference ${ref}`);}}}

const jsFiles=(await readdir(jsDir)).filter((name)=>name.endsWith('.js'));
for(const file of jsFiles){try{execFileSync(process.execPath,['--check',path.join(jsDir,file)],{stdio:'pipe'});}catch(error){failures.push(`${file}: JavaScript syntax error: ${error.stderr?.toString()||error.message}`);}}
const scriptsDir=path.join(root,'scripts');for(const file of (await readdir(scriptsDir)).filter((name)=>name.endsWith('.mjs'))){try{execFileSync(process.execPath,['--check',path.join(scriptsDir,file)],{stdio:'pipe'});}catch(error){failures.push(`${file}: JavaScript syntax error: ${error.stderr?.toString()||error.message}`);}}
const read=(relative)=>readFile(path.join(root,relative),'utf8');

const propertyHtml=await read('operator-dashboard.html'),propertyJs=await read('assets/js/operator-property-v2.js'),externalHtml=await read('operator-availability.html'),externalJs=await read('assets/js/operator-availability.js'),calendarJs=await read('assets/js/operator-calendar-v2.js'),calendarHardening=await read('assets/js/operator-calendar-hardening-v2.js'),reservationsJs=await read('assets/js/operator-reservations-v2.js'),analyticsJs=await read('assets/js/operator-analytics-v2.js'),listingsJs=await read('assets/js/operator-content-v2.js'),advancedJs=await read('assets/js/operator-listing-advanced-v2.js'),ratesJs=await read('assets/js/operator-rates-v2.js'),reviewsJs=await read('assets/js/operator-reviews-v2.js'),settingsJs=await read('assets/js/operator-settings-v2.js'),inboxJs=await read('assets/js/operator-inbox-v2.js'),paymentsJs=await read('assets/js/operator-payments-v2.js'),overviewJs=await read('assets/js/operator-overview-page-v2.js'),authJs=await read('assets/js/auth.js'),shellJs=await read('assets/js/operator-shell.js'),operatorCss=await read('assets/css/operator-v2.css');

if(!propertyHtml.includes('assets/js/operator-property-v2.js'))failures.push('Property page must load operator-property-v2.js');for(const id of ['listingForm','availabilityForm','promotionForm','availabilityRangeForm'])if(propertyHtml.includes(`id="${id}"`))failures.push(`Property page must not contain retired ${id}`);if(!propertyJs.includes("initializeOperatorPage('property')"))failures.push('Property controller must use shared V2 shell');if(propertyJs.includes('business_service_categories'))failures.push('Property must not overwrite listing service registrations');
if(externalHtml.includes('availabilityRangeForm')||externalHtml.includes('roomInventoryTable'))failures.push('External bookings page must not contain inventory editor');for(const rpc of ['create_external_accommodation_booking','cancel_external_accommodation_booking'])if(!externalJs.includes(rpc))failures.push(`External bookings missing ${rpc}`);
if(!calendarJs.includes('operator_set_room_calendar_range'))failures.push('Calendar must own room inventory/rate editing');if(!calendarJs.includes('Saving schedule…')||!calendarJs.includes('23505'))failures.push('Calendar recurring schedule double-submit protection missing');for(const rpc of ['operator_set_schedule_rule_state','operator_delete_schedule_rule','operator_upsert_schedule_exception','operator_delete_schedule_exception'])if(!calendarHardening.includes(rpc))failures.push(`Calendar hardening missing ${rpc}`);
for(const rpc of ['operator_update_booking','operator_quote_booking','operator_update_booking_note','operator_record_service_payment','operator_review_payment_reference'])if(!reservationsJs.includes(rpc))failures.push(`Reservations missing ${rpc}`);if(!reservationsJs.includes('Confirm price'))failures.push('Reservations must expose price confirmation');
for(const [name,source,needle] of [['Listings',listingsJs,"initializeOperatorPage('listings')"],['Rates',ratesJs,"initializeOperatorPage('rates')"],['Reviews',reviewsJs,"initializeOperatorPage('reviews')"],['Settings',settingsJs,"initializeOperatorPage('settings')"],['Inbox',inboxJs,"initializeOperatorPage('inbox')"],['Analytics',analyticsJs,"initializeOperatorPage('analytics')"],['Payments',paymentsJs,"initializeOperatorPage('payments')"]])if(!source.includes(needle))failures.push(`${name} must use its V2 controller`);
if(!analyticsJs.includes('operator_listing_analytics_v2'))failures.push('Analytics must use currency-safe V2 analytics');
if(!listingsJs.includes("from './operator-listing-advanced-v2.js'"))failures.push('Listings core must explicitly import advanced listing helpers');if(!listingsJs.includes("import './operator-room-media-v2.js'"))failures.push('Listings core must explicitly load room media');if(advancedJs.includes('client.from=function')||advancedJs.includes('originalFrom='))failures.push('Advanced Listings must not monkey-patch Supabase client.from');if(!listingsJs.includes('validateAdvancedListingForSubmit')||!listingsJs.includes('persistAdvancedListingDetails'))failures.push('Listings core must own advanced validation/persistence');
if(!overviewJs.includes(".eq('business_id',state.business.id)"))failures.push('Home must scope data to the selected business');if(!overviewJs.includes(".in('room_id',roomIds)"))failures.push('Home low-stock query must be limited to selected-business room IDs');
if(paymentsJs.includes("'\"':'&quot'"))failures.push('Payments HTML quote escaping is malformed');if(!paymentsJs.includes("storage.from('payment-proofs')"))failures.push('Payments proof viewer must use canonical payment-proofs bucket');
if(!operatorCss.startsWith("@import url('./operator-partner-extranet.css"))failures.push('Final operator styles must load synchronously through operator-v2.css');
for(const retired of retiredModules)if(authJs.includes(retired)||shellJs.includes(retired))failures.push(`Shared operator boot still references retired module ${retired}`);if(!shellJs.includes('operator-header-layout-v2.js?v=5')||!shellJs.includes('operator-notifications.js?v=5'))failures.push('Shared shell cache versions are stale');

const finalMigration=await read('supabase/migrations/20260825114106_operator_v2_audit_finalization.sql');for(const needle of ['schedule_rule_id','operator_upsert_schedule_exception','operator_delete_schedule_exception','payment_proofs_participant_select','is_active=(p_status=\'verified\')'])if(!finalMigration.includes(needle))failures.push(`Final audit migration missing ${needle}`);const calendarStaffMigration=await read('supabase/migrations/20260825114822_operator_calendar_staff_visibility.sql');if(!calendarStaffMigration.includes("'calendar'"))failures.push('Calendar staff visibility migration missing calendar permission');

const publicClient=await read('assets/js/supabase-client.js'),storage=await read('assets/js/storage.js');if(!publicClient.includes('persistSession: false')||!publicClient.includes('requirePublicSupabase'))failures.push('Isolated anonymous public client missing');if(!storage.includes('signedPublicImageUrl')||!storage.includes('requirePublicSupabase'))failures.push('Public media must use isolated anonymous client');
const manta=await read('assets/js/manta-planner.js'),tripPlanner=await read('assets/js/trip-planner-service.js'),tripResults=await read('assets/js/trip-results.js'),mantaCss=await read('assets/css/manta-planner.css');if(!manta.includes("'aria-label':'Open Visit Baa Trip Planner'"))failures.push('Manta launcher accessible name missing');if(!mantaCss.includes('prefers-reduced-motion'))failures.push('Manta reduced-motion handling missing');for(const requirement of ['trip-results.html','baa_manta_search'])if(!manta.includes(requirement))failures.push(`Manta results navigation missing ${requirement}`);for(const requirement of ['Add This Trip','Why These Options?','See Alternatives','recalculateJourney'])if(!tripResults.includes(requirement))failures.push(`Trip results requirement missing ${requirement}`);for(const requirement of ['recommendedActivityIsland','plannedActivityDates'])if(!tripPlanner.includes(requirement))failures.push(`Trip planner requirement missing ${requirement}`);
const serveConfig=JSON.parse(await read('serve.json'));if(serveConfig.cleanUrls!==false)failures.push('serve.json: cleanUrls must stay disabled');
const scanFiles=[...htmlFiles,...jsFiles.map((x)=>`assets/js/${x}`),'config.example.js','.env.example'];for(const file of scanFiles){const source=await read(file);if(/eyJ[a-zA-Z0-9_-]{20,}\.[a-zA-Z0-9_-]{20,}/.test(source)||/sb_secret_[a-zA-Z0-9_-]{10,}/.test(source))failures.push(`${file}: possible secret key detected`);}
if(failures.length){console.error(`Static checks failed (${failures.length}):`);failures.forEach((failure)=>console.error(`- ${failure}`));process.exit(1);}console.log(`Static checks passed: ${htmlFiles.length} HTML pages, ${jsFiles.length} JavaScript modules. Operator V2 workflows, migrations and safety guards are current.`);
